default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: admin_website_redone_development
  username: postgres
  password: postgres

# production:
#   <<: *default
#   database: admin_website_redone_production
#   username: admin_website_redone
#   password: <%= ENV['ADMIN_WEBSITE_REDONE_DATABASE_PASSWORD'] %>
